# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/icecube/Work/Vulkan-Again2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/icecube/Work/Vulkan-Again2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube/Work/Vulkan-Again2/CMakeFiles /home/icecube/Work/Vulkan-Again2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/icecube/Work/Vulkan-Again2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VulkanAgain2

# Build rule for target.
VulkanAgain2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VulkanAgain2
.PHONY : VulkanAgain2

# fast build rule for target.
VulkanAgain2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/build
.PHONY : VulkanAgain2/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

lib/vkbootstrap/VkBootstrap.o: lib/vkbootstrap/VkBootstrap.cpp.o
.PHONY : lib/vkbootstrap/VkBootstrap.o

# target to build an object file
lib/vkbootstrap/VkBootstrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/lib/vkbootstrap/VkBootstrap.cpp.o
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.o

lib/vkbootstrap/VkBootstrap.i: lib/vkbootstrap/VkBootstrap.cpp.i
.PHONY : lib/vkbootstrap/VkBootstrap.i

# target to preprocess a source file
lib/vkbootstrap/VkBootstrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/lib/vkbootstrap/VkBootstrap.cpp.i
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.i

lib/vkbootstrap/VkBootstrap.s: lib/vkbootstrap/VkBootstrap.cpp.s
.PHONY : lib/vkbootstrap/VkBootstrap.s

# target to generate assembly for a file
lib/vkbootstrap/VkBootstrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/lib/vkbootstrap/VkBootstrap.cpp.s
.PHONY : lib/vkbootstrap/VkBootstrap.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/vke_descriptors.o: src/vke_descriptors.cpp.o
.PHONY : src/vke_descriptors.o

# target to build an object file
src/vke_descriptors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_descriptors.cpp.o
.PHONY : src/vke_descriptors.cpp.o

src/vke_descriptors.i: src/vke_descriptors.cpp.i
.PHONY : src/vke_descriptors.i

# target to preprocess a source file
src/vke_descriptors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_descriptors.cpp.i
.PHONY : src/vke_descriptors.cpp.i

src/vke_descriptors.s: src/vke_descriptors.cpp.s
.PHONY : src/vke_descriptors.s

# target to generate assembly for a file
src/vke_descriptors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_descriptors.cpp.s
.PHONY : src/vke_descriptors.cpp.s

src/vke_device.o: src/vke_device.cpp.o
.PHONY : src/vke_device.o

# target to build an object file
src/vke_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_device.cpp.o
.PHONY : src/vke_device.cpp.o

src/vke_device.i: src/vke_device.cpp.i
.PHONY : src/vke_device.i

# target to preprocess a source file
src/vke_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_device.cpp.i
.PHONY : src/vke_device.cpp.i

src/vke_device.s: src/vke_device.cpp.s
.PHONY : src/vke_device.s

# target to generate assembly for a file
src/vke_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_device.cpp.s
.PHONY : src/vke_device.cpp.s

src/vke_engine.o: src/vke_engine.cpp.o
.PHONY : src/vke_engine.o

# target to build an object file
src/vke_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_engine.cpp.o
.PHONY : src/vke_engine.cpp.o

src/vke_engine.i: src/vke_engine.cpp.i
.PHONY : src/vke_engine.i

# target to preprocess a source file
src/vke_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_engine.cpp.i
.PHONY : src/vke_engine.cpp.i

src/vke_engine.s: src/vke_engine.cpp.s
.PHONY : src/vke_engine.s

# target to generate assembly for a file
src/vke_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_engine.cpp.s
.PHONY : src/vke_engine.cpp.s

src/vke_images.o: src/vke_images.cpp.o
.PHONY : src/vke_images.o

# target to build an object file
src/vke_images.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_images.cpp.o
.PHONY : src/vke_images.cpp.o

src/vke_images.i: src/vke_images.cpp.i
.PHONY : src/vke_images.i

# target to preprocess a source file
src/vke_images.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_images.cpp.i
.PHONY : src/vke_images.cpp.i

src/vke_images.s: src/vke_images.cpp.s
.PHONY : src/vke_images.s

# target to generate assembly for a file
src/vke_images.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_images.cpp.s
.PHONY : src/vke_images.cpp.s

src/vke_initializers.o: src/vke_initializers.cpp.o
.PHONY : src/vke_initializers.o

# target to build an object file
src/vke_initializers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_initializers.cpp.o
.PHONY : src/vke_initializers.cpp.o

src/vke_initializers.i: src/vke_initializers.cpp.i
.PHONY : src/vke_initializers.i

# target to preprocess a source file
src/vke_initializers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_initializers.cpp.i
.PHONY : src/vke_initializers.cpp.i

src/vke_initializers.s: src/vke_initializers.cpp.s
.PHONY : src/vke_initializers.s

# target to generate assembly for a file
src/vke_initializers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_initializers.cpp.s
.PHONY : src/vke_initializers.cpp.s

src/vke_pipelines.o: src/vke_pipelines.cpp.o
.PHONY : src/vke_pipelines.o

# target to build an object file
src/vke_pipelines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_pipelines.cpp.o
.PHONY : src/vke_pipelines.cpp.o

src/vke_pipelines.i: src/vke_pipelines.cpp.i
.PHONY : src/vke_pipelines.i

# target to preprocess a source file
src/vke_pipelines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_pipelines.cpp.i
.PHONY : src/vke_pipelines.cpp.i

src/vke_pipelines.s: src/vke_pipelines.cpp.s
.PHONY : src/vke_pipelines.s

# target to generate assembly for a file
src/vke_pipelines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_pipelines.cpp.s
.PHONY : src/vke_pipelines.cpp.s

src/vke_scene.o: src/vke_scene.cpp.o
.PHONY : src/vke_scene.o

# target to build an object file
src/vke_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_scene.cpp.o
.PHONY : src/vke_scene.cpp.o

src/vke_scene.i: src/vke_scene.cpp.i
.PHONY : src/vke_scene.i

# target to preprocess a source file
src/vke_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_scene.cpp.i
.PHONY : src/vke_scene.cpp.i

src/vke_scene.s: src/vke_scene.cpp.s
.PHONY : src/vke_scene.s

# target to generate assembly for a file
src/vke_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_scene.cpp.s
.PHONY : src/vke_scene.cpp.s

src/vke_shader.o: src/vke_shader.cpp.o
.PHONY : src/vke_shader.o

# target to build an object file
src/vke_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_shader.cpp.o
.PHONY : src/vke_shader.cpp.o

src/vke_shader.i: src/vke_shader.cpp.i
.PHONY : src/vke_shader.i

# target to preprocess a source file
src/vke_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_shader.cpp.i
.PHONY : src/vke_shader.cpp.i

src/vke_shader.s: src/vke_shader.cpp.s
.PHONY : src/vke_shader.s

# target to generate assembly for a file
src/vke_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_shader.cpp.s
.PHONY : src/vke_shader.cpp.s

src/vke_swapchain.o: src/vke_swapchain.cpp.o
.PHONY : src/vke_swapchain.o

# target to build an object file
src/vke_swapchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_swapchain.cpp.o
.PHONY : src/vke_swapchain.cpp.o

src/vke_swapchain.i: src/vke_swapchain.cpp.i
.PHONY : src/vke_swapchain.i

# target to preprocess a source file
src/vke_swapchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_swapchain.cpp.i
.PHONY : src/vke_swapchain.cpp.i

src/vke_swapchain.s: src/vke_swapchain.cpp.s
.PHONY : src/vke_swapchain.s

# target to generate assembly for a file
src/vke_swapchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_swapchain.cpp.s
.PHONY : src/vke_swapchain.cpp.s

src/vke_system.o: src/vke_system.cpp.o
.PHONY : src/vke_system.o

# target to build an object file
src/vke_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_system.cpp.o
.PHONY : src/vke_system.cpp.o

src/vke_system.i: src/vke_system.cpp.i
.PHONY : src/vke_system.i

# target to preprocess a source file
src/vke_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_system.cpp.i
.PHONY : src/vke_system.cpp.i

src/vke_system.s: src/vke_system.cpp.s
.PHONY : src/vke_system.s

# target to generate assembly for a file
src/vke_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_system.cpp.s
.PHONY : src/vke_system.cpp.s

src/vke_window.o: src/vke_window.cpp.o
.PHONY : src/vke_window.o

# target to build an object file
src/vke_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_window.cpp.o
.PHONY : src/vke_window.cpp.o

src/vke_window.i: src/vke_window.cpp.i
.PHONY : src/vke_window.i

# target to preprocess a source file
src/vke_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_window.cpp.i
.PHONY : src/vke_window.cpp.i

src/vke_window.s: src/vke_window.cpp.s
.PHONY : src/vke_window.s

# target to generate assembly for a file
src/vke_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VulkanAgain2.dir/build.make CMakeFiles/VulkanAgain2.dir/src/vke_window.cpp.s
.PHONY : src/vke_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... VulkanAgain2"
	@echo "... lib/vkbootstrap/VkBootstrap.o"
	@echo "... lib/vkbootstrap/VkBootstrap.i"
	@echo "... lib/vkbootstrap/VkBootstrap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/vke_descriptors.o"
	@echo "... src/vke_descriptors.i"
	@echo "... src/vke_descriptors.s"
	@echo "... src/vke_device.o"
	@echo "... src/vke_device.i"
	@echo "... src/vke_device.s"
	@echo "... src/vke_engine.o"
	@echo "... src/vke_engine.i"
	@echo "... src/vke_engine.s"
	@echo "... src/vke_images.o"
	@echo "... src/vke_images.i"
	@echo "... src/vke_images.s"
	@echo "... src/vke_initializers.o"
	@echo "... src/vke_initializers.i"
	@echo "... src/vke_initializers.s"
	@echo "... src/vke_pipelines.o"
	@echo "... src/vke_pipelines.i"
	@echo "... src/vke_pipelines.s"
	@echo "... src/vke_scene.o"
	@echo "... src/vke_scene.i"
	@echo "... src/vke_scene.s"
	@echo "... src/vke_shader.o"
	@echo "... src/vke_shader.i"
	@echo "... src/vke_shader.s"
	@echo "... src/vke_swapchain.o"
	@echo "... src/vke_swapchain.i"
	@echo "... src/vke_swapchain.s"
	@echo "... src/vke_system.o"
	@echo "... src/vke_system.i"
	@echo "... src/vke_system.s"
	@echo "... src/vke_window.o"
	@echo "... src/vke_window.i"
	@echo "... src/vke_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

